services:
  server1:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: Peer_A
    environment:
      - CONTAINER_NAME=Peer A
      - TERM=linux
    ports:
      - "1515:1515/udp"
    networks:
      net:
        ipv4_address: 172.21.0.2

  server2:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: Peer_B
    environment:
      - CONTAINER_NAME=Peer B
      - TERM=linux
    ports:
      - "1616:1616/udp"
    networks:
      net:
        ipv4_address: 172.21.0.3

  server3:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: Peer_C
    environment:
      - CONTAINER_NAME=Peer C
      - TERM=linux
    ports:
      - "1717:1717/udp"
    networks:
      net:
        ipv4_address: 172.21.0.4

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24